version: '3'
services:
  django-api:
    build: django_admin/app
    image: django-api:prod
    volumes:
      - static:/opt/app/static
    depends_on:
      - postgres
    env_file:
      - settings/.env.api
    expose:
      - "8000"

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/config:/etc/nginx/conf.d:ro
      - static:/data/static/:ro
    depends_on:
      - django-api
    ports:
      - "81:80"

  postgres-db:
    image: postgres:latest
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - settings/.env.database

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data

  elastic:
    image: elasticsearch:8.6.2
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

volumes:
  static:
  postgres-data:
  redis-data:
  elastic-data:

